//DEPLOYED YES OR NO?
DEPLOYED=true

//DB
CONNECTION_STR=jdbc:postgresql://db:5432/
DB_NAME=teamplanner
DB_USERNAME=postgres
DB_PASSWORD=rovelt123

//JWT
ISSUER=TeamPlanner
TOKEN_EXPIRE_TIME=86400000
SECRET_KEY=supersecretkey12345678901234567890