#### ======== GET DATA ========

### GET ALL ANNOUNCEMENTS
GET {{url}}/announcements
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}

### GET ANNOUNCEMENT BY ID
GET {{url}}/announcement/1
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}


#### ======== CREATE ========

POST {{url}}/announcement
Content-Type: application/json
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}

{
  "title": "Møde",
  "content": "Der er personalemøde fredag kl 18"
}


#### ======== UPDATE ========

PUT {{url}}/announcement/1
Content-Type: application/json
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}

{
  "content": "Mødet er flyttet til kl 19"
}


#### ======== DELETE ========

DELETE {{url}}/announcement/1
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}