#### ======== GET DATA ========

### GET ALL ANNOUNCEMENTS
GET {{url}}/announcements
Authorization: Bearer {{token}}

### GET ANNOUNCEMENT BY ID
GET {{url}}/announcement/1
Authorization: Bearer {{token}}


#### ======== CREATE ========

POST {{url}}/announcement
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Møde",
  "content": "Der er personalemøde fredag kl 18"
}


#### ======== UPDATE ========

PUT {{url}}/announcement/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "content": "Mødet er flyttet til kl 19"
}


#### ======== DELETE ========

DELETE {{url}}/announcement/1
Authorization: Bearer {{token}}