#### ======== GET DATA ========

### GET ALL HOLIDAYS
GET {{url}}/holidays
Authorization: Bearer {{token}}


#### ======== REQUEST HOLIDAY ========

POST {{url}}/holiday
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "start": "2026-07-01",
  "end": "2026-07-10"
}


#### ======== UPDATE HOLIDAY ========

PUT {{url}}/holiday/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "start": "2026-07-02",
  "end": "2026-07-12"
}


#### ======== APPROVE HOLIDAY (CHEF) ========

POST {{url}}/holiday/1/approve
Authorization: Bearer {{token}}


#### ======== REJECT HOLIDAY (CHEF) ========

POST {{url}}/holiday/1/reject
Authorization: Bearer {{token}}