#### ======== GET DATA ========

### GET ALL MESSAGES
GET {{url}}/messages
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}

### GET CONVERSATION
GET {{url}}/conversation/2
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}


#### ======== SEND MESSAGE ========

POST {{url}}/message/2
Content-Type: application/json
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}

{
  "content": "Går det godt habibi?"
}


#### ======== UPDATE MESSAGE ========

PUT {{url}}/message/2
Content-Type: application/json
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}

{
  "content": "Redigeret besked"
}


#### ======== DELETE MESSAGE ========

DELETE {{url}}/message/2
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}