#### ======== GET DATA ========

### GET ALL RESPONSIBILITIES
GET {{url}}/responsibilities
Authorization: Bearer {{token}}

### GET RESPONSIBILITY BY ID
GET {{url}}/responsibility/1
Authorization: Bearer {{token}}

### GET RESPONSIBILITY BY NAME
GET {{url}}/responsibility/name/Chauffør
Authorization: Bearer {{token}}


#### ======== CREATE ========

POST {{url}}/responsibility/Bar
Content-Type: application/json
Authorization: Bearer {{token}}



#### ======== UPDATE ========

PUT {{url}}/responsibility/Bar/update/Chauffør2
Authorization: Bearer {{token}}



#### ======== DELETE ========

DELETE {{url}}/responsibility/Bar
Authorization: Bearer {{token}}