#### ======== GET DATA ========

### GET ALL RESPONSES
GET {{url}}/responses
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}

### GET RESPONSE BY ID
GET {{url}}/response/3
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}

### GET RESPONSES BY SHIFT REQUEST
GET {{url}}/responses/user/1
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}

### GET RESPONSES BY REQUEST
GET {{url}}/responses/request/1
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}

### ACCEPT BY ID
PUT {{url}}/response/1/accept
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}

### REJECT BY ID
PUT {{url}}/response/1/reject
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}

### NO RESPONSE BY ID
PUT {{url}}/response/1/no-response
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}

#### ======== UPDATE RESPONSE ========
### You can update the following: status, shift_request, user_id
### Yes, you can update multiple at a time!
### ==================================
PUT {{url}}/response/1
Content-Type: application/json
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}

{
  "status": "NO_RESPONSE"
}

#### ======== DELETE RESPONSE ========
DELETE {{url}}/response/1
Content-Type: application/json
Authorization: Bearer {{token}}
