#### ======== GET DATA ========

### GET ALL RESPONSES
GET {{url}}/responses
Authorization: Bearer {{token}}

### GET RESPONSE BY ID
GET {{url}}/response/3
Authorization: Bearer {{token}}

### GET RESPONSES BY SHIFT REQUEST
GET {{url}}/responses/user/1
Authorization: Bearer {{token}}

### GET RESPONSES BY REQUEST
GET {{url}}/responses/request/1
Authorization: Bearer {{token}}

### ACCEPT BY ID
PUT {{url}}/response/1/accept
Authorization: Bearer {{token}}

### REJECT BY ID
PUT {{url}}/response/1/reject
Authorization: Bearer {{token}}

### NO RESPONSE BY ID
PUT {{url}}/response/1/no-response
Authorization: Bearer {{token}}

#### ======== UPDATE RESPONSE ========
### You can update the following: status, shift_request, user_id
### Yes, you can update multiple at a time!
### ==================================
PUT {{url}}/response/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "NO_RESPONSE"
}

#### ======== DELETE RESPONSE ========
DELETE {{url}}/response/1
Authorization: Bearer {{token}}
