
### =========================
### GET ALL SHIFTS
### =========================
GET {{url}}/shifts
Authorization: Bearer {{token}}


### =========================
### GET SHIFT BY ID
### /shift/{id}
### =========================
GET {{url}}/shift/2
Authorization: Bearer {{token}}


### =========================
### GET SHIFTS BY DATE
### /shifts/date/yyyy-mm-dd
### =========================
GET {{url}}/shifts/date/2026-03-28
Authorization: Bearer {{token}}


### =========================
### GET SHIFTS BY USER
### /shifts/user/{id}
### =========================
GET {{url}}/shifts/user/3
Authorization: Bearer {{token}}


### =========================
### CREATE SHIFT (CHEF)
### Must enter: user_id, title, date(yyyy-mm-dd), startetime(24h time), end_time(24h time)
### =========================
POST {{url}}/shift
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "user_id": "3",
  "title": "Bar",
  "date": "2026-03-02",
  "start_time": "10:00",
  "end_time": "16:00"
}


### =========================
### UPDATE SHIFT (CHEF)
### You can update the following: date, start_time, end_time, owner, title
### Yes, you can update multiple at a time!
### =========================
PUT {{url}}/shift/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "date": "2026-02-01"
}


### =========================
### DELETE SHIFT (CHEF)
### /shifts/{id}
### =========================
DELETE {{url}}/shift/4
Authorization: Bearer {{token}}


### =========================
### CREATE SCHEDULE (CHEF)
### Must enter user_id and how far in months you want to scedule for
### Must also enter all days in the week (Monday, tuesday, wednesday, thursday, friday, saturday and sunday) in following format:
### "<day_name>": {"title": <title>, "start_time": <24h time>, "end_time": <24h time>, "offDay": <true/false>}
### =========================
POST {{url}}/shift/schedule
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "user_id": 2,
  "months": 1,

  "monday": {
    "title": "Arbejde",
    "start_time": "08:00",
    "end_time": "16:00",
    "offDay": false
  },
  "tuesday": {
    "title": "Arbejde",
    "start_time": "08:00",
    "end_time": "16:00",
    "offDay": false
  },
  "wednesday": {
    "title": "Fri",
    "start_time": null,
    "end_time": null,
    "offDay": true
  },
  "thursday": {
    "title": "Arbejde",
    "start_time": "08:00",
    "end_time": "16:00",
    "offDay": false
  },
  "friday": {
    "title": "Arbejde",
    "start_time": "08:00",
    "end_time": "16:00",
    "offDay": false
  },
  "saturday": {
    "offDay": true
  },
  "sunday": {
    "offDay": true
  }
}
