#### ======== GET DATA ========

### GET ALL SHIFT REQUESTS
GET {{url}}/shiftrequests
Authorization: Bearer {{token}}

### GET SHIFT REQUEST BY ID
GET {{url}}/shiftrequest/1
Authorization: Bearer {{token}}


#### ======== CREATE REQUEST ========

POST {{url}}/shiftrequest/1
Authorization: Bearer {{token}}


#### ======== TAKE SHIFT ========

POST {{url}}/shiftrequest/8/take
Authorization: Bearer {{token}}


#### ======== DECLINE SHIFT ========

POST {{url}}/shiftrequest/8/decline
Authorization: Bearer {{token}}


#### ======== DELETE REQUEST ========

DELETE {{url}}/shiftrequest/7
Authorization: Bearer {{token}}


#### ======== UPDATE REQUEST ========

PUT {{url}}/shiftrequest/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "SOLVED"
}

### You can update the following: status, requester_id, shift_id
### Yes, you can update multiple at a time!