#### ======== GET DATA ========

### GET ALL SHIFTS
GET {{url}}/shifts
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}

### GET SHIFT BY ID
GET {{url}}/shift/1
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}

### GET SHIFTS BY DATE
GET {{url}}/shifts/date/2026-03-13
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}

### GET SHIFTS BY USER
GET {{url}}/shifts/user/2
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}


#### ======== CREATE SHIFT (CHEF) ========

POST {{url}}/shift
Content-Type: application/json
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}

{
  "user_id": "6",
  "title": "Bar",
  "date": "2026-05-01",
  "start_time": "10:00",
  "end_time": "16:00"
}


#### ======== UPDATE SHIFT ========

PUT {{url}}/shift/3
Content-Type: application/json
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}

{
  "start_time": "19:00",
  "end_time": "20:00"
}

### You can update the following: date, start_time, end_time, owner, title
### Yes, you can update multiple at a time!


#### ======== DELETE SHIFT ========

DELETE {{url}}/shift/3
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}