#### ======== GET DATA ========

### GET ALL SHIFT REQUESTS
GET {{url}}/shiftrequests
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}

### GET SHIFT REQUEST BY ID
GET {{url}}/shiftrequest/1
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}


#### ======== CREATE REQUEST ========

POST {{url}}/shiftrequest/1
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}


#### ======== TAKE SHIFT ========

POST {{url}}/shiftrequest/1/take
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}


#### ======== DELETE REQUEST ========

DELETE {{url}}/shiftrequest/1
Cookie: JSESSIONID=node0wq02f5tbj4m4ddbuj6axh29r0.node0
Authorization: Bearer {{token}}