### =========================
### GET ALL SHIFT REQUESTS
### =========================
GET {{url}}/shiftrequests
Authorization: Bearer {{token}}


### =========================
### GET SHIFT REQUEST BY ID
### =========================
GET {{url}}/shiftrequest/1
Authorization: Bearer {{token}}


### =========================
### CREATE SHIFT REQUEST
### =========================
POST {{url}}/shiftrequest/1
Authorization: Bearer {{token}}


### =========================
### DELETE SHIFT REQUEST
### =========================
DELETE {{url}}/shiftrequest/7
Authorization: Bearer {{token}}

### =========================
### UPDATE REQUEST
### You can update the following: status, requester_id, shift_id
### Yes, you can update multiple at a time!
### =========================
PUT {{url}}/shiftrequest/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "SOLVED"
}