### =========================
### LOGIN
### =========================
POST {{url}}/users/auth/login
Content-Type: application/json

{
  "username": "Rovelt",
  "password": "Rovelt"
}

> {%
    var data = JSON.parse(responseBody);
    token = data.token;
%}

### =========================
### LOGOUT
### =========================
POST {{url}}/users/auth/logout
Authorization: Bearer {{token}}


### =========================
### REGISTER USER
### =========================
POST {{url}}/users/auth/register
Content-Type: application/json

{
  "name": "Rovelt",
  "username": "Rovelt",
  "password": "Rovelt",
  "password_repeat": "Rovelt"
}


### =========================
### GET ALL USERS
### =========================
GET {{url}}/users
Authorization: Bearer {{token}}


### =========================
### GET USER BY ID
### =========================
GET {{url}}/user/1
Authorization: Bearer {{token}}


### =========================
### GET USER BY USERNAME
### =========================
GET {{url}}/user/by-username/Rovelt
Authorization: Bearer {{token}}


### =========================
### UPDATE USERNAME
### =========================
PUT {{url}}/user/update-username
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "newUsername": "Rovelt",
  "password": "Rovelt"
}


### =========================
### UPDATE PASSWORD
### =========================
PUT {{url}}/user/update-password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "oldPassword": "Rovelt123",
  "newPassword": "Rovelt",
  "newPassword_repeat": "Rovelt"
}


### =========================
### DELETE USER (SELF)
### =========================
DELETE {{url}}/user/delete
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "password1": "Rovelt",
  "password2": "Rovelt"
}


### =========================
### FORCE DELETE USER (CHEF)
### =========================
DELETE {{url}}/user/force-delete/4
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "confirm_username": "Rovelt"
}